Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

sample_array = np.array([[1, 2, 3], [4, 5, 6]])
sample_list = [1, 2, 3, 4]

empty_array= np.empty((2,2))
ones_array = np.ones((4, 2), dtype=int)
fill_array = np.full((3, 3), fill_value=7)
zeros_like_array= np.zeros_like(sample_array)
ones_like_array= np.ones_like(sample_array)
numpy_array= np.array(sample_list)


print("Empty Array (2x2):\n", empty_array)
print("\nAll Ones Array (4x2):\n", ones_array)
print("\nArray Filled with Value 7 (3x3):\n", fill_array)
print("\nZeros Array with Same Shape as Sample Array:\n", zeros_like_array)
print("\nOnes Array with Same Shape as Sample Array:\n", ones_like_array)
print("\nConverted List to Numpy Array:\n", numpy_array)


Empty Array (2x2):
 [[4.67348588e-310 0.00000000e+000]
 [4.61328143e-194 6.76862096e-310]]

All Ones Array (4x2):
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]

Array Filled with Value 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Sample Array:
 [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as Sample Array:
 [[1 1 1]
 [1 1 1]]

Converted List to Numpy Array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

array_10_to_49= np.arange(10,50)
matrix_0_to_8= np.arange(9).reshape(3,3)
identity_matrix= np.eye(3)
random_array = np.random.random(30)
mean_value = random_array.mean()
random_10x10= np.random.random((10,10))
min_value = random_10x10.min()
max_value = random_10x10.max()
zero_array = np.zeros(10)
zero_array[4] = 1
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array= arr[::-1]
_3x3matrix = np.ones((3,3))
_3x3matrix[1:-1,1:-1]=0
_8x8matrix = np.zeros((8,8), dtype=int)
_8x8matrix[1::2, ::2]=1
_8x8matrix[::2, 1::2]=1


print("Array from 10 to 49:\n", array_10_to_49)
print("\n3x3 Matrix from 0 to 8:\n", matrix_0_to_8)
print("\n3x3 Identity Matrix:\n", identity_matrix)
print("\nRandom Array of size 30:\n", random_array)
print("Mean of Random Array:", mean_value)
print("\n10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("\nZero Array with 5th element replaced by 1:\n", zero_array)
print("\nReversed Array:\n", reversed_array)
print("\n2D Array with 1 on border and 0 inside:\n", _3x3matrix)
print("\n8x8 Checkerboard Pattern:\n", _8x8matrix)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.81227525 0.91224637 0.45577745 0.5583347  0.410674   0.32264416
 0.44971654 0.5858184  0.05938464 0.96514601 0.20634434 0.05440051
 0.22274083 0.2596701  0.72040592 0.46898899 0.12237101 0.82487787
 0.28039186 0.4160969  0.05826987 0.01987527 0.04615201 0.57545746
 0.14686432 0.71452896 0.06397231 0.05052118 0.38311433 0.88396458]
Mean of Random Array: 0.40170087070947963

10x10 Random Array:
 [[0.62667135 0.49288523 0.21360836 0.84021465 0.60713759 0.63184122
  0.78323153 0.60981016 0.27536981 0.33920663]
 [0.75914977 0.98378434 0.03233451 0.80029629 0.25498418 0.82393773
  0.63966195 0.96130801 0.44754424 0.80567709]
 [0.09279825 0.08024993 0.23651531 0.95798802 0.18831401 0.33913231
  0.62499818 0.8

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition_result = x + y
print("Addition of x and y:")
print(addition_result)

subtraction_result = x - y
print("\nSubtraction of x and y:")
print(subtraction_result)

multiplication_result = x * 3
print("\nMultiplying x by 3:")
print(multiplication_result)

square_result = np.square(x)
print("\nSquare of each element in x:")
print(square_result)

dot_product_vw = np.dot(v, w)
dot_product_xv = np.dot(x, v)
dot_product_xy = np.dot(x, y)

print("\nDot product of v and w:", dot_product_vw)
print("Dot product of x and v:", dot_product_xv)
print("Dot product of x and y:", dot_product_xy)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("\nConcatenating x and y along row:")
print(concat_xy_row)
print("\nConcatenating v and w along column:")
print(concat_vw_column)

try:
    concat_xv = np.concatenate((x, v), axis=1)
except ValueError as e:
    print("\nError when concatenating x and v:", e)

Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplying x by 3:
[[ 3  6]
 [ 9 15]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]

Concatenating x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v and w along column:
[[ 9 11]
 [10 12]]

Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

# Given matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I (Identity Matrix)
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1 = Identity Matrix:")
print(identity_matrix)

# 2. Prove AB != BA (Check if AB equals BA)
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:")
print(AB)
print("\nBA:")
print(BA)

# Check if AB == BA
if np.array_equal(AB, BA):
    print("\nAB equals BA")
else:
    print("\nAB does not equal BA")

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T:")
print(AB_T)
print("\nB^T * A^T:")
print(BT_AT)

# Check if (AB)^T == B^T * A^T
if np.array_equal(AB_T, BT_AT):
    print("\n(AB)^T equals B^T * A^T")
else:
    print("\n(AB)^T does not equal B^T * A^T")

# 4. Solve the system of equations using Inverse Method (AX = B)
# System of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system in matrix form: AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X = A^-1 * B
X = np.dot(np.linalg.inv(A_eq), B_eq)

print("\nSolution of the system of equations (X = [x, y, z]):")
print(X)


A * A^-1 = Identity Matrix:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

AB does not equal BA

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

(AB)^T equals B^T * A^T

Solution of the system of equations (X = [x, y, z]):
[ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# 1. Element-wise Addition

# Using Python lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()
python_list_addition_time = end_time - start_time
print(f"Python list element-wise addition time: {python_list_addition_time:.5f} seconds")

# Using NumPy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
numpy_sum = array1 + array2
end_time = time.time()
numpy_array_addition_time = end_time - start_time
print(f"NumPy array element-wise addition time: {numpy_array_addition_time:.5f} seconds")

# 2. Element-wise Multiplication

# Using Python lists
start_time = time.time()
list_multiply = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()
python_list_multiplication_time = end_time - start_time
print(f"Python list element-wise multiplication time: {python_list_multiplication_time:.5f} seconds")

# Using NumPy arrays
start_time = time.time()
numpy_multiply = array1 * array2
end_time = time.time()
numpy_array_multiplication_time = end_time - start_time
print(f"NumPy array element-wise multiplication time: {numpy_array_multiplication_time:.5f} seconds")

# 3. Dot Product

# Using Python lists
start_time = time.time()
list_dot_product = sum([list1[i] * list2[i] for i in range(1000000)])
end_time = time.time()
python_list_dot_product_time = end_time - start_time
print(f"Python list dot product time: {python_list_dot_product_time:.5f} seconds")

# Using NumPy arrays
start_time = time.time()
numpy_dot_product = np.dot(array1, array2)
end_time = time.time()
numpy_array_dot_product_time = end_time - start_time
print(f"NumPy array dot product time: {numpy_array_dot_product_time:.5f} seconds")

# 4. Matrix Multiplication

# Create two 1000x1000 matrices using Python lists
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

# Using Python lists for matrix multiplication
start_time = time.time()
matrix_product = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
python_matrix_multiplication_time = end_time - start_time
print(f"Python list matrix multiplication time: {python_matrix_multiplication_time:.5f} seconds")

# Using NumPy arrays for matrix multiplication
matrix1_np = np.arange(1000000).reshape(1000, 1000)
matrix2_np = np.arange(1000000).reshape(1000, 1000)

start_time = time.time()
numpy_matrix_product = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
numpy_matrix_multiplication_time = end_time - start_time
print(f"NumPy array matrix multiplication time: {numpy_matrix_multiplication_time:.5f} seconds")


Python list element-wise addition time: 0.20724 seconds
NumPy array element-wise addition time: 0.00729 seconds
Python list element-wise multiplication time: 0.20316 seconds
NumPy array element-wise multiplication time: 0.00800 seconds
Python list dot product time: 0.21407 seconds
NumPy array dot product time: 0.00339 seconds
Python list matrix multiplication time: 258.62029 seconds
NumPy array matrix multiplication time: 2.31827 seconds
